// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 22 Jan 2018 16:56:03 JST.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package nk provides Go bindings for nuklear.h — a small ANSI C gui library.
*/
package nk
